### PR TITLE
1135 allow selection of axioms

### LINKED ISSUE #1135: Allow selection of axioms
Allow the user to select a set of axioms to use for proving a theorem.

### PR DESCRIPTION
**Pull request by eugenk**
This shall fix #1135. It adds the manual selection of axioms for proving.

-

The branch of this pull request is based on:
* 1318-create_hets_prove_fixtures_for_different_configurations (#1324) 
* 1287-parse_szs_status_from_prover_output (#1319)

The first commit of this branch is:
Allow to select axioms.	083053b

### CODE REVIEW

**Comment by tillmo** [comment]
Currently, I cannot prove theorems in this branch.
I checkout the branch, merge in #1342, do a `rake db:migrate:clean` and `rake db:seed`, and then try a proof. I get:
```
2015-05-19T19:49:25.974Z 10717 TID-12tqw0 ERROR: Actor crashed!
NoMethodError: undefined method `proof_attempts' for nil:NilClass
        /home/till/web2.0/ontohub/lib/hets/prove/prove_evaluation_helper.rb:8:in `
fill_proof_attempt_from_hash'
        /home/till/web2.0/ontohub/lib/hets/prove/prove_evaluator.rb:79:in `goal_en
d'
        /home/till/web2.0/ontohub/lib/hets/base_evaluator.rb:54:in `block in proce
ss'
        /home/till/web2.0/ontohub/lib/hets/base_evaluator.rb:53:in `each'
        /home/till/web2.0/ontohub/lib/hets/base_evaluator.rb:53:in `process'
        /home/till/web2.0/ontohub/lib/hets/json_parser.rb:37:in `call_back'
        /home/till/web2.0/ontohub/lib/hets/prove/parser.rb:34:in `select_callback'
        /home/till/web2.0/ontohub/lib/hets/json_parser.rb:71:in `object_end'
        /home/till/web2.0/ontohub/lib/hets/json_parser.rb:29:in `block in initiali
ze_parser_hooks'
```

**Comment by eugenk** [comment]
I rebased staging after merging #1343 and that error doesn't seem to appear now.

**Comment by tillmo** [comment]
:+1: (modulo travis...)

**Comment by eugenk** [comment]
I rebased on #1324, where I added two commits. I assume it's still okay to merge this one as soon as #1324 gets merged.
